name: quality

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  flake-check:
    name: Flake Check
    runs-on: native
    steps:
      - uses: actions/checkout@v4
      - run: nix flake check
